### ISSUE TITLE
gather data for Devilstable

### ISSUE THREAD

**Issue by flicksolutions** [DHBern/presentation_parzival#19]
The `<Devilstable>` component accepts data in the following form:

```
[
        {
            label: 'D',
            values: [
               true, true, true, false, false, false, true, true, false, ...
            ]
        },
        {
            label: 'n',
            values: [
                true, true, true, false, false, false, true, true, ...
            ]
        }
];
```
`values` is an array of size 827 with boolean values indicating wether or not a _Dreissiger_ is present in this manuscript at this index. Alternatively a more human-readable could also be accepted, where values is an array of arrays of 2-tuples. Each tuple signifies the beginning of a block where the _Dreissiger_ are present. e.g. [18, 25] means: verses 18 - 25 are present.

`label` can be either handle or sigil - whatever is easier to retrieve.

This data needs to be gathered via XSLT and presented as a JSON.
The source are all _Textzeugen_ and _Fragmente_ but not the _Fassungen_

**Comment by pdaengeli** [comment]
Here you go: [contiguous_ranges.json](https://github.com/DHBern/presentation_parzival/files/14740730/contiguous_ranges.json)

This format contains the ranges both sequentially and as tuples. Which one do you prefer, `values` or `v-tuples`?

```json
  {
    "label": "fr16",
    "values": [
      [ 622, 623 ],
      [ 625, 626, 627, 628 ],
      [ 630, 631 ]
    ],
    "v-tuples": [
      [ 622, 623 ],
      [ 625, 628 ],
      [ 630, 631 ]
    ]
  },
  {
    "label": "fr17",
    "values": [ [ 160, 161, 162, 163, 164, 165, 166, 167, 168 ] ],
    "v-tuples": [ [ 160, 168 ] ]
  },
  ```

**Comment by flicksolutions** [comment]
wow, that was fast! =)
I prefer v-tuples of the two. Because in the end I need uniform Arrays of length 827 so a transformation is necessary anyways - therefore let's go for the the more compact format. :-)

thank you very much!

**Comment by pdaengeli** [comment]
Good, `v-tuples` is now `values` (and what was `values` is gone): [contiguous_ranges.json](https://github.com/DHBern/presentation_parzival/files/14741355/contiguous_ranges.json)

The fragments are not ordered nicely (`fr19`, `fr2`, `fr20`), but it shouldn't matter (I can fix it with custom code or a custom collation, but it is a waste of effort IMO).

**Comment by flicksolutions** [comment]
perfect! Thank you!

**Comment by flicksolutions** [comment]
Sorry I have to reopen the issue. The data contains error: There are suspisiusly many chunks ending in 99... e.g. 
```
    {
      "values": [ [ 1, 99 ] ],
      "label": "o"
    },
    ```
    
 I only checked for o, but most of them ending in 99 might be wrong. Something must have gone wrong...

**Comment by flicksolutions** [comment]
seems like your export works for fr, but not for the others. anything that's not fr is 1 to 99 exept for vv...

**Comment by flicksolutions** [comment]
looks good now! thanks! =)
