### ISSUE TITLE
Use data from https://dhbern.github.io/parzival-static-api

### ISSUE THREAD

**Issue by pdaengeli** [DHBern/presentation_parzival#20]
The following static endpoints are ready for consumption/integration:

- [x] https://dhbern.github.io/parzival-static-api/api/json/contiguous_ranges.json
- [x] https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-page.json

---

Furthermore there is a flat collection of all TEI files available at:

* https://github.com/DHBern/parzival-static-api/tree/master/dist/api/tei/flattened
* https://dhbern.github.io/parzival-static-api/api/tei/flattened/{$id}.xml

Given the lacking Git control in eXist it would be good to use these files in order to have a single source of truth. Consequently, we should remove these files from the `parzival_data` repo and keep only the ODD file and other TEIPublisher-related stuff there.

---

Any additional needs are best recorded in a [new issue at `parzival-static-api`](https://github.com/DHBern/parzival-static-api/issues/new/choose).

**Comment by flicksolutions** [comment]
could you restructure the metadata-ms-page.json?
The most performant would be to get separate files per siglum. ie. https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-page/${id}.json

**Comment by pdaengeli** [comment]
Perhaps this is implemented already with the [`split_output` param](https://github.com/DHBern/parzival-static-api/blob/master/src/util/metadata-ms-page.xsl#L25).

If I set it to true I get the following output:

<details><summary>tree</summary>

```
$ tree metadata-ms-page
metadata-ms-page
├── d.json
├── fr10.json
├── fr11.json
├── fr12.json
├── fr13.json
├── fr14.json
├── fr15.json
├── fr16.json
├── fr17.json
├── fr18.json
├── fr19.json
├── fr1.json
├── fr20.json
├── fr21.json
├── fr22.json
├── fr23.json
├── fr24.json
├── fr25.json
├── fr26.json
├── fr27.json
├── fr28.json
├── fr29.json
├── fr2.json
├── fr30.json
├── fr31.json
├── fr32.json
├── fr33.json
├── fr34.json
├── fr35.json
├── fr36.json
├── fr37.json
├── fr38.json
├── fr39.json
├── fr3.json
├── fr40.json
├── fr41.json
├── fr42.json
├── fr43.json
├── fr44.json
├── fr45.json
├── fr46.json
├── fr47.json
├── fr48.json
├── fr49.json
├── fr4.json
├── fr50.json
├── fr51.json
├── fr52.json
├── fr53.json
├── fr54.json
├── fr55.json
├── fr56.json
├── fr57.json
├── fr58.json
├── fr59.json
├── fr5.json
├── fr60.json
├── fr61.json
├── fr62.json
├── fr63.json
├── fr64.json
├── fr65.json
├── fr66.json
├── fr67.json
├── fr68.json
├── fr69.json
├── fr6.json
├── fr70.json
├── fr71.json
├── fr72.json
├── fr7.json
├── fr8.json
├── fr9.json
├── g.json
├── i.json
├── l.json
├── m.json
├── mk.json
├── nk.json
├── o.json
├── ok.json
├── q.json
├── r.json
├── t.json
├── u.json
├── v.json
├── vv.json
├── w.json
└── z.json

0 directories, 89 files
```

</details>

<details><summary>sample: <code>d.json</code>, <code>fr1.json</code></summary>

* [d.json](https://github.com/user-attachments/files/15515580/d.json)
* [fr1.json](https://github.com/user-attachments/files/15515581/fr1.json)

</details>

Would that work? Then I change the default and commit the JSON files.

**Comment by flicksolutions** [comment]
yes, that's what I need! It's the same files that [are used atm](https://github.com/DHBern/presentation_parzival/tree/main/src/lib/metadata-ms-page) Thank you!

**Comment by pdaengeli** [comment]
Indeed, diffing shows that they are identitcal:

<details><summary><code>fr1</code></summary>

```diff
diff <(curl -s https://raw.githubusercontent.com/DHBern/presentation_parzival/main/src/lib/metadata-ms-page/fr1.json) metadata-ms-page/fr1.json 
515c515
<     "generated-by": "file:\/data\/WORK\/DH-unibe\/parzival\/parzival-static-backend-prep\/src\/util\/metadata-ms-page.xsl",
---
>     "generated-by": "file:\/data\/WORK\/DH-unibe\/parzival\/parzival-static-api\/src\/util\/metadata-ms-page.xsl",
517c517
<     "generated-on": "2024-04-23T23:56:30.502349+02:00",
---
>     "generated-on": "2024-05-31T17:00:29.507889+02:00",
```

</details>


<details><summary><code>d</code> (more complex)</summary>

```diff
diff <(curl -s https://raw.githubusercontent.com/DHBern/presentation_parzival/main/src/lib/metadata-ms-page/d.json) metadata-ms-page/d.json 
26200c26200
<     "generated-by": "file:\/data\/WORK\/DH-unibe\/parzival\/parzival-static-backend-prep\/src\/util\/metadata-ms-page.xsl",
---
>     "generated-by": "file:\/data\/WORK\/DH-unibe\/parzival\/parzival-static-api\/src\/util\/metadata-ms-page.xsl",
26202c26202
<     "generated-on": "2024-04-23T23:56:30.502349+02:00",
---
>     "generated-on": "2024-05-31T17:00:29.507889+02:00",

```

</details>

I'll commit and push shortly.

**Comment by pdaengeli** [comment]
Good to go now, e.g. https://dhbern.github.io/parzival-static-api/api/json/metadata-ms-page/fr1.json

**Comment by pdaengeli** [comment]
How about defining a constant for `https://dhbern.github.io/parzival-static-api/api/` and use it in [`+server.js#L9`](https://github.com/DHBern/presentation_parzival/blob/f0da7bd807eefc0fadd52010afc0ad8c8895df50/src/routes/api/json/metadata-ms-page/%5Bsigla%5D/%5Bthirties%5D/%5Bverse%5D/%2Bserver.js#L9) and [`+page.js#L5`](https://github.com/DHBern/presentation_parzival/blob/62a3f3e764d96282f69a68c0716cea509171a89f/src/routes/%2Bpage.js#L5)?
