### ISSUE TITLE
Sorting entries in hsverz

### ISSUE THREAD

**Issue by pdaengeli** [DHBern/presentation_parzival#25]
Some entries are not in the right position:

![image](https://github.com/user-attachments/assets/8eee939d-8789-4fc8-956a-5564db6b974f)
![image](https://github.com/user-attachments/assets/48ea81a1-f36c-4600-b4a4-08c500fb02de)

The was caused by filename-based sorting in the data generation. It was fixed in https://github.com/DHBern/parzival-static-api/commit/82ecb8d53e79ffb75291f7b6532025259c07e558, so a simple build of the app should do the trick.

**Comment by flicksolutions** [comment]
fixed with rebuild
